# Generated by Django 3.2.4 on 2023-05-08 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Superpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SuperVillain',
            fields=[
                ('superhero_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.superhero')),
                ('nemesis', models.CharField(max_length=100)),
            ],
            bases=('api.superhero',),
        ),
        migrations.RenameField(
            model_name='superhero',
            old_name='alter_ego',
            new_name='alias',
        ),
        migrations.AddField(
            model_name='superhero',
            name='publisher',
            field=models.CharField(default='NN', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superhero',
            name='locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location'),
        ),
        migrations.AddField(
            model_name='superhero',
            name='super_powers',
            field=models.ManyToManyField(to='api.Superpower'),
        ),
    ]
