# Generated by Django 3.2.4 on 2023-06-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='first_appearance',
            field=models.CharField(default=2023, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.CharField(default=2023, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.CharField(default='luis', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(default='luis', max_length=100),
            preserve_default=False,
        ),
    ]
