# Generated by Django 3.2.4 on 2023-06-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230623_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='superhero_name',
            field=models.CharField(default='superhero', max_length=100),
            preserve_default=False,
        ),
    ]
