# Generated by Django 3.2.4 on 2023-05-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230509_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superhero',
            old_name='locations',
            new_name='location',
        ),
    ]
